### PR TITLE
chore(script): add installation script

### PR DESCRIPTION
**Pull request by anler**
# PR Prelude

Thank you for contributing to sheikah! :)

**Please fill in this template (by putting an `x` inside
the brackets) _before_ filing your PR:**

- [X] I have read and understood [CODE_OF_CONDUCT][code] document.
- [X] I have read and understood [CONTRIBUTING][cont] document.
- [X] I have read and understood [STYLEGUIDE][style] document.
- [X] I have included tests for the changes in my PR. If not, I have included a
  rationale for why I haven't.
- [X] My code is formatted and is accepted by `yarn fmt`.
- [X] **I understand my PR may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

# Why this change is necessary and useful

[Please explain **in detail** why the changes in this PR are needed.]

A one-line command to clone and install Sheikah for development:
```
sh -c "$(curl https://raw.githubusercontent.com/anler/sheikah/install-script/scripts/install)"
```

[code]: https://github.com/witnet/sheikah/blob/master/.github/CODE_OF_CONDUCT.md
[cont]: https://github.com/witnet/sheikah/blob/master/.github/CONTRIBUTING.md
[style]: https://github.com/witnet/sheikah/blob/master/docs/STYLEGUIDE.md

### CODE REVIEW

**Comment by aesedepece** [comment]
I'm not directly against this, but I think we should only offer it as an alternate installation method.
Open question: is `npm install sheikah` a possibility?

**Comment by aesedepece** [comment]
For example, we created another Electrum app a few years ago and the preferred instalation method was npm itself:
https://github.com/trailbot/client/blob/master/GETTING-STARTED.md#installation

**Comment by anler** [comment]
This is not an _installation_ method itself, maybe we should change that terminology, this the way of getting up to speed to start developing in Sheikah.

I'm not sure npm is suitable for us, it is mainly for distributing packages as source code or command line programs, not for distributing development projects (for that we already have github) nor applications that can be installed (our releases).

**Comment by aesedepece** [comment]
I'm OK with it if:
- we use that exact wording: "Getting up to speed to start developing in Sheikah"
- we explain that the script will simply clone the repo and install all the dependencies
- we stress that the standard way to start is to clone and `yarn` by hand.

**Comment by anler** [comment]
I think we better close this for the moment since it is not a priority.

**Pull request closed without merging**
