### PR TITLE
refactor(issue 403): rename wallets to walletInfos

### LINKED ISSUE #403: Rename getWallets to getWalletInfos and .wallets to .versionedWalletInfos
#### Motivation
Current naming for some methods and data structures can be misleading. This namely happens with:
- `getWallets` API method: it doesn't really get wallets but a list of info objects about the existing wallets
- `wallets` key of app state: it doesn't really contain wallets but a versioned object containing a list of info object about the existing wallets (this property is called `infos`)

We shall improve this names for the sake of clarity.

#### Deliverables
_A potential PR closing this issue shall provide:_
- `getWallets` API method, renamed as `getWalletInfos`.
- `wallets` key of app state, renamed as `walletInfos`

### PR DESCRIPTION
**Pull request by anler**
# PR Prelude

Thank you for contributing to sheikah! :)

**Please fill in this template (by putting an `x` inside
the brackets) _before_ filing your PR:**

- [X] I have read and understood [CODE_OF_CONDUCT][code] document.
- [X] I have read and understood [CONTRIBUTING][cont] document.
- [X] I have read and understood [STYLEGUIDE][style] document.
- [X] I have included tests for the changes in my PR. If not, I have included a
  rationale for why I haven't.
- [X] My code is formatted and is accepted by `yarn fmt`.
- [X] **I understand my PR may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

# Why this change is necessary and useful

[Please explain **in detail** why the changes in this PR are needed.]

Fixes #403

**IMPORTANT** This PR introduces breaking changes, wallets created before this PR won't be available because they were stored under `wallets` and now they are being stored under `walletInfos`

[code]: https://github.com/witnet/sheikah/blob/master/.github/CODE_OF_CONDUCT.md
[cont]: https://github.com/witnet/sheikah/blob/master/.github/CONTRIBUTING.md
[style]: https://github.com/witnet/sheikah/blob/master/docs/STYLEGUIDE.md

### CODE REVIEW

**Comment by anler** [comment]
That's because the key in the storage is also renamed to `walletInfo`, should I leave it as `wallet`?

**Comment by anler** [comment]
hmm I was wrong, is not because of that

**Comment by aesedepece** [comment]
No, that's perfectly OK. Let's just tag the commit as having breaking changes :ok_hand:

**Comment by aesedepece** [comment]
Merged as 05d242766b108be808526d8b0fea6698eb1a41ea.

**Pull request closed without merging**
