### PR TITLE
feat: add external link to the block explorer for the witnet tx

### LINKED ISSUE #1733: Add block explorer link
Add link to the data request transaction hash to redirect to the block explorer.

### PR DESCRIPTION
**Pull request by gabaldon**
close #1733

### CODE REVIEW

**Comment by aesedepece** [comment]
This is missing the link for the transaction too (currently only links to the block page)

**Review by aesedepece — CHANGES_REQUESTED** [review]
This is missing the link for the transaction too (currently only links to the block page)

**Comment by Tommytrg** [comment]
We could also show a button next to the copy address one to open the address in the block explorer

**Review by aesedepece — APPROVED** [review]
Works like a charm! :rocket:

**Review by Tommytrg — APPROVED** [review]

**Review by Tommytrg — APPROVED** [review]

**Pull request merged**
