### PR TITLE
chore(background): update public nodes urls

### PR DESCRIPTION
**Pull request by gabaldon**

### CODE REVIEW

**Comment by aeweda** [comment]
@gabaldon why are there files committed besides `constants.ts` ?

**Review by Tommytrg — CHANGES_REQUESTED** [review]
Could you remove the changes from the yarn.lock?

**Comment by aeweda** [comment]
> Could you remove the changes from the yarn.lock?

Was literally typing the same comment xD

**Review by aeweda — APPROVED** [review]
LGTM

**Review by Tommytrg — APPROVED** [review]

**Pull request merged**
